version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: fintech-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintech_db

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fintech_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: fintech-adminer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  backend:
    container_name: fintech-backend

    build:
      context: ./backend

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fintech_db?schema=public
      JWT_SECRET: troque-em-producao
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173

    command: sh -c "npx prisma migrate deploy && npm run prisma:seed && node dist/src/main.js"

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    restart: unless-stopped

  frontend:
    container_name: fintech-frontend

    build:
      context: ./frontend

    depends_on:
      - backend

    environment:
      VITE_API_URL: http://localhost:3000

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    restart: unless-stopped

volumes:
  postgres_data: